site_name: parasol-insurance-app
site_description: Parasol Insurance Application
repo_url: https://gitlab-gitlab.apps.cluster-j2gsb.j2gsb.sandbox2537.opentlc.com/development/parasol-insurance-app
edit_uri: edit/master/docs

plugins:
  - techdocs-core

# Note for content editors, edit only the section below
nav:
  - Onboard a developer to OpenShift: onboard-openshift.md
  - Application Migration:
      - Migration Process Overview: application-migration/migration-process-overview.md
      - Migration Process Steps: application-migration/migration-process-steps.md
      - Learning Path for Developers: application-migration/learning-path-for-developers.md
